"""add email column

Revision ID: 58a9f85b3eef
Revises: e7ec6b3a06ff
Create Date: 2025-06-09 02:27:22.210206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a9f85b3eef'
down_revision: Union[str, None] = 'e7ec6b3a06ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Сначала добавляем как nullable
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    
    # Заполняем существующие записи
    op.execute("UPDATE users SET email = 'temp@example.com' WHERE email IS NULL")

    op.alter_column('users', 'is_banned',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_banned',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
