"""add ban system fields

Revision ID: e7ec6b3a06ff
Revises: 1ebcc5e210ed
Create Date: 2025-05-30 01:38:00.380320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ec6b3a06ff'
down_revision: Union[str, None] = '1ebcc5e210ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('ban_reason', sa.String(), nullable=True))
    op.add_column('users', sa.Column('banned_untill', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banned_untill')
    op.drop_column('users', 'ban_reason')
    op.drop_column('users', 'is_banned')
    # ### end Alembic commands ###
